### PR TITLE
PR for two issues related to README.md

### PR DESCRIPTION
**Pull request by edreamleo**
**#125**

- [x] Add a "Demo Videos" section containing *duplicates* of links to demo videos.

**#128**

- [x] Revise tables relating to key-bindings, especially bindings that change focus.
- [x] Add a comment that arrow keys put focus in outline by default.

### CODE REVIEW

**Comment by edreamleo** [comment]
@boltex These changes are only suggestions :-)

**Comment by boltex** [comment]
@edreamleo Thank you! 

( The documentation for a project like Leo / LeoJS is almost a project in itself! 😄   )

**Comment by boltex** [comment]
@edreamleo Sorry for not looking into this merge request earlier, thanks for merging it - it's quite a good addition and clarification to the documentation! (I've barely adjusted one sentence!)

In fact, I'm going to copy/paste that directly into the LeoInteg readme ! 😄

**Comment by edreamleo** [comment]
@boltex Glad you like the changes.

**Pull request merged**
